services:
  filamenthub:
    container_name: filamenthub
    build: .
    restart: unless-stopped
    ports:
      - "8085:8085"


    network_mode: host


    environment:
      FILAMENTHUB_DB_PATH: /app/data/filamenthub.db
      PYTHONPATH: /app
    volumes:
      - /mnt/user/appdata/filamenthub/data:/app/data
      - /mnt/user/appdata/filamenthub/logs:/app/logs
    entrypoint: ["./entrypoint.sh"]
